# Generated by Django 4.2.7 on 2024-01-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='nid',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
