# Generated by Django 4.2.7 on 2024-01-15 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0003_profile'),
        ('transaction', '0003_remove_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passenger.useraccount'),
        ),
    ]
