# Generated by Django 4.2.7 on 2024-01-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedule',
            name='train_date',
            field=models.CharField(max_length=100),
        ),
    ]
