# Generated by Django 4.2.7 on 2024-01-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_alter_shedule_train_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='ticket_number',
            field=models.CharField(max_length=3),
        ),
    ]
