# Generated by Django 4.2.7 on 2024-01-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_alter_seat_ticket_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='price',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='ticket_number',
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
