# Generated by Django 4.2.7 on 2024-01-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0005_remove_seat_price_remove_seat_ticket_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=3, null=True),
        ),
    ]
