# Generated by Django 4.2.7 on 2024-01-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0006_alter_seat_seat_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='train',
        ),
        migrations.AddField(
            model_name='train',
            name='seat',
            field=models.ManyToManyField(to='train.seat'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=3),
        ),
    ]
