# Generated by Django 4.2.7 on 2024-01-15 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0007_remove_seat_train_train_seat_alter_seat_seat_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyticket',
            name='seat',
        ),
    ]
