# Generated by Django 4.2.7 on 2024-01-15 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0008_remove_buyticket_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='seat',
        ),
        migrations.AddField(
            model_name='seat',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='train.train'),
        ),
    ]
