# Generated by Django 4.2.7 on 2024-01-16 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0010_remove_buyticket_balance_after_borrow_buyticket_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyticket',
            name='seat',
        ),
        migrations.CreateModel(
            name='ReviewAgain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rating', models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], max_length=10)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.train')),
            ],
        ),
        migrations.AddField(
            model_name='buyticket',
            name='seat',
            field=models.ManyToManyField(to='train.seat'),
        ),
    ]
