# Generated by Django 4.2.7 on 2024-01-16 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0011_remove_buyticket_seat_reviewagain_buyticket_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewagain',
            name='train',
        ),
        migrations.DeleteModel(
            name='BuyTicket',
        ),
        migrations.DeleteModel(
            name='ReviewAgain',
        ),
    ]
